// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInstalled(arg1) {
  return window['go']['app']['App']['CheckInstalled'](arg1);
}

export function CheckWinget() {
  return window['go']['app']['App']['CheckWinget']();
}

export function GetApps() {
  return window['go']['app']['App']['GetApps']();
}

export function GetAppsWithUpdates() {
  return window['go']['app']['App']['GetAppsWithUpdates']();
}

export function GetInstalledApps() {
  return window['go']['app']['App']['GetInstalledApps']();
}

export function InstallApps(arg1) {
  return window['go']['app']['App']['InstallApps'](arg1);
}

export function IsAdmin() {
  return window['go']['app']['App']['IsAdmin']();
}

export function UninstallApp(arg1) {
  return window['go']['app']['App']['UninstallApp'](arg1);
}

export function UpgradeApp(arg1) {
  return window['go']['app']['App']['UpgradeApp'](arg1);
}
