// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckInstalled(arg1:string):Promise<boolean>;

export function CheckWinget():Promise<boolean>;

export function GetApps():Promise<Array<models.AppData>>;

export function GetAppsWithUpdates():Promise<Array<string>>;

export function GetInstalledApps():Promise<Array<string>>;

export function InstallApps(arg1:Array<string>):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function UninstallApp(arg1:string):Promise<void>;

export function UpgradeApp(arg1:string):Promise<void>;
